platform: linux

image_resource: 
  type: docker-image
  source: 
   repository: ruby
   tag: 2.3.0 

# define the things we need to run the task

inputs: 
- name: flight-school

run: 
  path: ./flight-school/ci/test.sh
